quarkus:
  application:
    name: Gestion de Medicamentos
    version: 1.0-SNAPSHOT

  http:
    port: 8620
    host: localhost
    # Se eliminó el root-path para que responda en la raíz (ej: /formulas)

  datasource:
    db-kind: h2
    username: admin
    password: 12345
    jdbc:
      file: ./data/gdocentes_db

  hibernate-orm:
    schema-management:
      strategy: drop-and-create
    log:
      sql: true

  log:
    level: INFO
    console:
      enabled: true
      format: "%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] (%t) %s%e%n"
    file:
      enabled: true
      path: logs/gestudiantes.log
      format: "%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] (%t) %s%e%n"
      rotation:
        max-file-size: 5M
        max-backup-index: 5
        file-suffix: yyyy-MM-dd

  swagger-ui:
    enabled: true
    always-include: true
    path: "/swagger-ui"

mp:
  openapi:
    extensions:
      smallrye:
        info:
          title: "Gestion de medicamentos"
          version: "1.1.0"

"%prod":
  quarkus:
    http:
      port: ${PORT:8080}
      host: 0.0.0.0
      cors: true # Habilitado para permitir peticiones del frontend

    datasource:
      db-kind: h2
      username: ${DB_USER:admin}
      password: ${DB_PASSWORD:12345}
      jdbc:
        url: jdbc:h2:mem:gdocentes_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

    hibernate-orm:
      schema-management:
        strategy: drop-and-create
      log:
        sql: false

    swagger-ui:
      enabled: true
      always-include: true
      path: /swagger-ui

    log:
      level: INFO
      console:
        enabled: true
      file:
        enabled: false